from commons.citymap import Coordinate
from commons.auto_str import auto_str
from commons.my_enum import OrderStatus
from datetime import datetime


@auto_str
class Order:
    """
    Food delivery orders.
    """
    
    def __init__(self, uuid, start_location: Coordinate, end_location: Coordinate, time: datetime, description=""):
        self.uuid = uuid                        # Unique ID
        self.start_location = start_location    # Start location
        self.end_location = end_location        # End location
        self.generate_time = time               # Generated time
        self.deliver_time = None                # Delivered time
        self.status = None                      # Current status: 1.WAITING 2.ACCEPTED 3.DELIVERING 4.DELIVERED
        self.description = description          # Order description
        self.generate()
        
    def generate(self):
        """The order is generated by order generator and is waiting for drones to accept"""
        self.status = OrderStatus.WAITING
        # print(f"[{datetime.now()}] Order '{self.uuid}' is created")
    
    def accept(self):
        """The order is accepted by a drone and the drone is heading to the restaurant to pick up order"""
        self.status = OrderStatus.ACCEPTED
        # print(f"[{datetime.now()}] Order '{self.uuid}' is accepted")
    
    def deliver(self):
        """The order is being delivered by a drone"""
        self.status = OrderStatus.DELIVERING
        # print(f"[{datetime.now()}] Order '{self.uuid}' is being delivered")
        
    def complete(self):
        """The order is complete and food is delivered"""
        self.deliver_time = datetime.now()
        self.status = OrderStatus.COMPLETE
        # print(f"[{datetime.now()}] Order '{self.uuid}' is complete")
        

if __name__ == '__main__':
    print("Use OrderGenerator to test Order")
